#!/bin/bash

name=""

unlock_screen(){
	adb shell input keyevent  26	#press power key 
	sleep 1
	adb shell input keyevent  82    #unlock screen
	sleep 1
}


screen_check(){
        echo $(adb shell dumpsys power | grep 'mHolding') | grep "mHoldingDisplaySuspendBlocker=true"
        r=$?
        if [ $r -ne 0 ];then
                unlock_screen
        fi
}



take_photo(){
	adb shell rm -rf /sdcard/DCIM/Camera/*.jpg			#delete the all photo
	sleep 0.5
	adb shell am start -a android.media.action.STILL_IMAGE_CAMERA 	#start camera
	sleep 2
	adb shell input keyevent  27	#take photo
	sleep 2
}

download_file(){
	adb shell mv /sdcard/DCIM/Camera/*.jpg /sdcard/DCIM/Camera/test.jpg	#rename the photo
	sleep 1
	adb pull /sdcard/DCIM/Camera/test.jpg . 				#down load the photo
}

get_sn(){
	now=`TZ='Asia/Shanghai' date +"%Y%m%d-%H%M%S"`
	for ((i = 0; i < 10; i++ )); do
		id1=$(python3 barcode.py 0)
		id2=$(python3 barcode.py 1)
                [[ $id1 == J* ]] && [[ $id2 == M* ]] && name=$id2-$id1-T${now} && break
                [[ $id1 == A* ]] && [[ $id2 == M* ]] && name=$id2-$id1-T${now} && break
                [[ $id1 == J* ]] && [[ $id2 == N* ]] && name=$id2-$id1-T${now} && break
                [[ $id1 == A* ]] && [[ $id2 == N* ]] && name=$id2-$id1-T${now} && break
                [[ $id1 == M* ]] && [[ $id2 == J* ]] && name=$id1-$id2-T${now} && break
                [[ $id1 == M* ]] && [[ $id2 == A* ]] && name=$id1-$id2-T${now} && break
                [[ $id1 == N* ]] && [[ $id2 == J* ]] && name=$id1-$id2-T${now} && break
                [[ $id1 == N* ]] && [[ $id2 == A* ]] && name=$id1-$id2-T${now} && break

	done
}
upload_picture(){
	mv test.jpg $name.jpg
	python3 alicloud_upload.py $name.jpg $name.jpg
	r=$?
	return $r
}
config-pin p9_22 gpio
screen_check
leds all on
while [ 1 ]
do
    status=$(gpio input 2)
    if [ $status -eq 1 ]; then
	leds all off
        take_photo
        download_file
        get_sn
        upload_picture
        r=$?
        rm -rf *.jpg
        if [ $r -eq 0 ]; then
            leds all on
        fi
    fi
done
