#!/bin/bash

unlocal_screen(){
	adb shell input keyevent  26	#press power key 
	sleep 1
	adb shell input keyevent  82	#unlock screen
	sleep 1
}


take_photo(){
	adb shell rm -rf /sdcard/DCIM/Camera/*.jpg			#delete the all photo
	sleep 0.5
	adb shell am start -a android.media.action.STILL_IMAGE_CAMERA 	#start camera
	sleep 0.5
	adb shell input keyevent  27	#take photo
	sleep 0.5
}

download_file(){
	adb shell mv /sdcard/DCIM/Camera/*.jpg /sdcard/DCIM/Camera/test.jpg	#rename the photo
	sleep 1
	adb pull /sdcard/DCIM/Camera/test.jpg . 				#down load the photo
}

get_sn(){
	id1=$(python barcode.py)
	echo "----------$id1"
	id2=$(python barcode.py)
	echo "----------$id2"
#	name=$id1_$id2
	echo $name
}

#unlocal_screen
#take_photo
#download_photo
get_sn
